
### Get All Authors
GET http://localhost:5000/api/authors



### Add New Author
POST http://localhost:5000/api/authors
Content-Type: application/json

{
    "name":"Vivek Dutta Mishra",
    "biography":"Author of the Lost Epic series",
    "photo":"vivek.png"
}

### Update an Author
PUT http://localhost:5000/api/authors/vivek
Content-Type: application/json

{
    "id":"vivek",
    "name":"Vivek Dutta Mishra",
    "biography":"Author of the Lost Epic series",
    "photo":"vivek.png"
}



### Get Author By Id
GET http://localhost:5000/api/authors/vivek-dutta-mishra



### Get Books by  Author
GET http://localhost:5000/api/authors/vivek-dutta-mishra/books